// +build !ignore_autogenerated

/*
Copyright 2020 Fairwinds

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlternateImageSource) DeepCopyInto(out *AlternateImageSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlternateImageSource.
func (in *AlternateImageSource) DeepCopy() *AlternateImageSource {
	if in == nil {
		return nil
	}
	out := new(AlternateImageSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlternateImageSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlternateImageSourceList) DeepCopyInto(out *AlternateImageSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AlternateImageSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlternateImageSourceList.
func (in *AlternateImageSourceList) DeepCopy() *AlternateImageSourceList {
	if in == nil {
		return nil
	}
	out := new(AlternateImageSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlternateImageSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlternateImageSourceSpec) DeepCopyInto(out *AlternateImageSourceSpec) {
	*out = *in
	if in.ImageSourceReplacements != nil {
		in, out := &in.ImageSourceReplacements, &out.ImageSourceReplacements
		*out = make([]ImageSourceReplacement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlternateImageSourceSpec.
func (in *AlternateImageSourceSpec) DeepCopy() *AlternateImageSourceSpec {
	if in == nil {
		return nil
	}
	out := new(AlternateImageSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlternateImageSourceStatus) DeepCopyInto(out *AlternateImageSourceStatus) {
	*out = *in
	if in.TargetsAvailable != nil {
		in, out := &in.TargetsAvailable, &out.TargetsAvailable
		*out = make([]Target, len(*in))
		copy(*out, *in)
	}
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlternateImageSourceStatus.
func (in *AlternateImageSourceStatus) DeepCopy() *AlternateImageSourceStatus {
	if in == nil {
		return nil
	}
	out := new(AlternateImageSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSourceReplacement) DeepCopyInto(out *ImageSourceReplacement) {
	*out = *in
	if in.EquivalentRepositories != nil {
		in, out := &in.EquivalentRepositories, &out.EquivalentRepositories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]Target, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSourceReplacement.
func (in *ImageSourceReplacement) DeepCopy() *ImageSourceReplacement {
	if in == nil {
		return nil
	}
	out := new(ImageSourceReplacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Target) DeepCopyInto(out *Target) {
	*out = *in
	out.Type = in.Type
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Target.
func (in *Target) DeepCopy() *Target {
	if in == nil {
		return nil
	}
	out := new(Target)
	in.DeepCopyInto(out)
	return out
}
